// Copyright 2026.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ui

import (
	"testing"

	"github.com/maybewaityou/fleetboard/internal/core/domain"
)

// TestAccountFormSubmitValid 验证必填字段齐全时 submit 触发 onSubmit 并带正确字段。
// ID 不再来自表单（新增时由 main.GenerateAccountID 生成），应留空。
func TestAccountFormSubmitValid(t *testing.T) {
	f := NewAccountForm()
	f.input(afFieldLabel).SetText("智谱")
	f.providerDropDown().SetCurrentOption(0) // glm
	f.input(afFieldTokenEnv).SetText("GLM_API_KEY")

	var got domain.Account
	called := false
	f.OnSubmit(func(acc domain.Account) { got = acc; called = true })
	f.submit()

	if !called {
		t.Fatal("submit did not fire OnSubmit for valid input")
	}
	if got.ID != "" {
		t.Errorf("ID should be empty from form (generated by main on save), got %q", got.ID)
	}
	if got.Provider != "glm" || got.TokenEnv != "GLM_API_KEY" || got.Label != "智谱" {
		t.Fatalf("submit fields wrong: %+v", got)
	}
}

// TestAccountFormSubmitRejectsMissingRequired 验证缺必填字段时 submit 不触发。
func TestAccountFormSubmitRejectsMissingRequired(t *testing.T) {
	f := NewAccountForm()
	// Label / Provider / TokenEnv 全留空
	called := false
	f.OnSubmit(func(domain.Account) { called = true })
	f.submit()
	if called {
		t.Fatal("submit must not fire when required fields (label/provider/token_env) are empty")
	}
}

// TestAccountFormProviderNoDefault 验证 Provider 下拉初始无预选（idx=-1，显示 placeholder）。
func TestAccountFormProviderNoDefault(t *testing.T) {
	f := NewAccountForm()
	idx, v := f.providerDropDown().GetCurrentOption()
	if idx != -1 || v != "" {
		t.Errorf("Provider should have no default (idx=-1, shows placeholder), got idx=%d v=%q", idx, v)
	}
}

// TestAccountFormPrefill 验证编辑场景下 Prefill 正确回填字段（不含 ID）。
func TestAccountFormPrefill(t *testing.T) {
	f := NewAccountForm()
	f.Prefill(domain.Account{ID: "x", Provider: "minimax", Label: "l", BaseURL: "http://b", TokenEnv: "T"})

	if idx, v := f.providerDropDown().GetCurrentOption(); v != "minimax" || idx != 1 {
		t.Errorf("provider not prefilled to minimax(idx1): idx=%d v=%q", idx, v)
	}
	if f.text(afFieldLabel) != "l" {
		t.Errorf("Label not prefilled: %q", f.text(afFieldLabel))
	}
	if f.text(afFieldTokenEnv) != "T" {
		t.Errorf("TokenEnv not prefilled: %q", f.text(afFieldTokenEnv))
	}
	if f.text(afFieldBaseURL) != "http://b" {
		t.Errorf("BaseURL not prefilled: %q", f.text(afFieldBaseURL))
	}
}

// TestAccountFormSubmitNewapi newapi 必填 AccessTokenEnv + UserID（TokenEnv 可空）。
func TestAccountFormSubmitNewapi(t *testing.T) {
	f := NewAccountForm()
	f.input(afFieldLabel).SetText("kuaipao")
	f.providerDropDown().SetCurrentOption(5) // newapi（providerOptions 第 6 项，idx=5）
	f.input(afFieldAccessTokenEnv).SetText("NEWAPI_AT")
	f.input(afFieldUserID).SetText("16002")

	var got domain.Account
	called := false
	f.OnSubmit(func(acc domain.Account) { got = acc; called = true })
	f.submit()

	if !called {
		t.Fatal("submit should fire for valid newapi (AccessTokenEnv+UserID)")
	}
	if got.AccessTokenEnv != "NEWAPI_AT" || got.UserID != "16002" {
		t.Fatalf("newapi creds not captured: %+v", got)
	}
}

// TestAccountFormSubmitNewapiRejectsMissing newapi 缺凭证不触发 submit。
func TestAccountFormSubmitNewapiRejectsMissing(t *testing.T) {
	f := NewAccountForm()
	f.input(afFieldLabel).SetText("kuaipao")
	f.providerDropDown().SetCurrentOption(5) // newapi
	f.input(afFieldAccessTokenEnv).SetText("NEWAPI_AT")
	// UserID 留空
	called := false
	f.OnSubmit(func(domain.Account) { called = true })
	f.submit()
	if called {
		t.Fatal("submit must not fire when newapi UserID missing")
	}
}

// TestAccountFormPrefillNewapi 验证 Prefill 回填 new-api 凭证字段。
func TestAccountFormPrefillNewapi(t *testing.T) {
	f := NewAccountForm()
	f.Prefill(domain.Account{
		Provider: "newapi", Label: "l", BaseURL: "http://b",
		AccessTokenEnv: "NEWAPI_AT", UserID: "16002",
	})
	if f.text(afFieldAccessTokenEnv) != "NEWAPI_AT" {
		t.Errorf("AccessTokenEnv not prefilled: %q", f.text(afFieldAccessTokenEnv))
	}
	if f.text(afFieldUserID) != "16002" {
		t.Errorf("UserID not prefilled: %q", f.text(afFieldUserID))
	}
}
